import Image from 'next/image'
import Head from 'next/head'

export default function Home() {
  return (
    <>
    <div>
      <Head>
        <title>codencodes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>

    <main>
      <div>
        <h1>Hello world!</h1>
      </div>
    </main>
    </>
  )
}
