import Navbar from '@/components/Navbar'
import Head from 'next/head'

export default function Home() {
  return (
    <>
    <div>
      <Head>
        <title>codencodes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
    </div>

    <main>
    </main>
    </>
  )
}
